# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Mark Hong
baseurl:        ""
url:            "https://hongsigner.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Mark Hong
  url:          https://hongsigner.github.io/
  email:        hongsigner@gmail.com  
  github:       hongsigner
  instagram:    @hongsigner

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/hongsigner/hongsigner.github.io
